### ISSUE TITLE
[🐞 BUG]: deleting wrong option in heuristic test

### ISSUE THREAD

**Issue by FernandaCasali** [ruxailab/RUXAILAB#435]
### Description 📝

When you click on delete the option, it always deletes the last option you have and not the one you want.

### Link 🔗

\src\components\molecules\OptionsTable.vue

### Steps to Reproduce 🔄

- 

### Screenshots 📸

- 

### Expected Behavior 🤔

- 

### Actual Behavior 😱

- 

### Environment 🌍

-

**Comment by LostSputnik** [comment]
Interested. Can i try?

**Comment by KarinePistili** [comment]
Yes, you can! Assigned @LostSputnik

**Comment by LostSputnik** [comment]
Hello, hope you're doing all right!
So I set up the project with firebase emulator and attempted to recreate the problem on my local system. I have some interesting observations that I wanted to discuss.

- The bug seems to be there only for options with no value, i.e the ones where we uncheck the `Has Value` checkbox.
- Deleting seems to work properly for options that do have a value
- For cases where both kinds of option exists, the bug is exclusive to the ones without values.

I tried a number of test cases to assess this, such as where there are options with value after the ones without, and vise versa, as well as checking if deleting one type of option affects the other.  I also checked combinations of the order of these two types of options to check if that had any effect. In all these, the above points seem to hold true. Here, I'm attaching a screen-recording so you can have a better insight, and also to make sure my process is aligned with the intended use.


https://github.com/ruxailab/RUXAILAB/assets/34897621/e2a6652e-0566-429f-b2f0-2ef8617e5d86


I plan to first look into those options that don't have value, and work my way up from there. Am I on the right track? Eager to hear your thoughts on this. Thanks!

@KarinePistili @FernandaCasali

**Comment by LostSputnik** [comment]
I went ahead and made the [PR](https://github.com/ruxailab/RUXAILAB/pull/441), so that we have a basis to discuss further. Please me know if it aligns with the requirements. Thanks again ^_^

**Comment by KarinePistili** [comment]
Thanks @LostSputnik !! We will test it out and ping you back with feedback!

**Comment by LostSputnik** [comment]
You're welcome @KarinePistili. I believe I also came across a bug related to editing the option description. Let's look at that once we're done with this first.
