### ISSUE TITLE
[🐞 BUG]: Is there a problem in the Description User Test 

### ISSUE THREAD

**Issue by saltykheera** [ruxailab/RUXAILAB#529]
### Description 📝

isn't the description written in the moderated test and unmoderated test should be reversed ?

![image](https://github.com/user-attachments/assets/69b8e866-1b95-4b9e-ba35-5d448b18f5d3)

### Link 🔗

https://ruxailab-prod.firebaseapp.com/createBlank

### Steps to Reproduce 🔄

create blank user test 

### Screenshots 📸

![image](https://github.com/user-attachments/assets/191c55b7-b0ce-43e7-992c-67b71092d7ad)

### Expected Behavior 🤔

![image](https://github.com/user-attachments/assets/e181f208-594d-4c09-98e2-5c80798e76ee)

### Actual Behavior 😱

![image](https://github.com/user-attachments/assets/328f7e55-8421-463f-a786-90a04187e521)

### Environment 🌍

components: createBlank

**Comment by ThatDeparted2061** [comment]
I don't think there is a bug here as far as I understand.
Live test will be moderated because it ll use user's webcam and mic to record live video and audio feed.
Where as the self test wont be so, since it is like a practice test which can be taken anywhere.
For these reasons I think this is not a bug.
